name: Ubuntu - lint & unit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run test
        run: ./gradlew test